FROM python:3.8-alpine

EXPOSE 5000/tcp

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ADD static ./static
COPY templates ./templates
COPY app.py .

CMD ["python", "./app.py"]
